spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/wqddg_fmsc?characterEncoding=utf-8
#      username: root
#      password: admin123
      username: wqddg
      password: 1314520
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.wqddg.entity